# produces redisfab/redis-py-cluster:6.2.6
FROM redis:6.2.6-buster

COPY create_cluster.sh /create_cluster.sh
RUN chmod +x /create_cluster.sh

EXPOSE 6372 6373 6374 6375 6376 6377

CMD [ "/create_cluster.sh"]
