name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'


filter-by-commitish: true
commitish: 6.0

pre-release: true

version-resolver:
  major:
    labels:
      - 'breakingchange'
  minor:
    labels:
      - 'feature'
      - 'deprecation'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'update-docs'
      - 'dependencies'
      - 'security'

autolabeler:
  - label: 'maintenance'
    files:
      - '*.md'
      - '.github/*'
  - label: 'bug'
    branch:
      - '/bug-.+'
  - label: 'maintenance'
    branch:
      - '/maintenance-.+'
  - label: 'feature'
    branch:
      - '/feature-.+'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🧪 Experimental Features'
    labels:
      - 'experimental'
  - title: '🔥 Breaking Changes'
    labels:
      - 'breakingchange'
  - title: '⚠️ Deprecations'
    labels:
      - 'deprecation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'dependencies'
      - 'techdebt'
      - 'docs-review'
      - 'update-docs'

change-template: '- $TITLE $AUTHOR (#$NUMBER)'

exclude-labels:
  - 'skip-changelog'

template: |
  # Changes

  $CHANGES

  ## Contributors
  We'd like to thank all the contributors who worked on this release!

  $CONTRIBUTORS

