#!/usr/bin/env python

from optparse import OptionParser
import os
import subprocess
import unittest
from redis_server import server


if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-x", "--executable", dest="redis_path", action="store",
        type="string", default=None, help="Path to the redis executable")
    parser.add_option("-c", "--conf", dest="conf", default=None,
                      help="Path to the redis configuration file.")

    (options, args) = parser.parse_args()

    server.configure(options.redis_path, options.conf)

    with server:
        from tests import all_tests
        tests = all_tests()
        results = unittest.TextTestRunner().run(tests)
