#!/usr/bin/env python
import unittest

# this is a work around to keep tests compatible across all the python versions
if not hasattr(unittest, "skipIf"):
    import unittest2 as unittest

from tests import all_tests


if __name__ == "__main__":
    tests = all_tests()
    results = unittest.TextTestRunner().run(tests)
