# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # ubuntu 64bit image
  config.vm.box = "hashicorp/precise64"

  # map the root of redis-py to /home/vagrant/redis-py
  config.vm.synced_folder "../", "/home/vagrant/redis-py"

  # install the redis server
  config.vm.provision :shell, :path => "../build_tools/bootstrap.sh"
  config.vm.provision :shell, :path => "../build_tools/build_redis.sh"
  config.vm.provision :shell, :path => "../build_tools/install_redis.sh"
  config.vm.provision :shell, :path => "../build_tools/install_sentinel.sh"
  config.vm.provision :file, :source => "../build_tools/.bash_profile", :destination => "/home/vagrant/.bash_profile"

  # setup forwarded ports
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  config.vm.network "forwarded_port", guest: 6380, host: 6380
  config.vm.network "forwarded_port", guest: 26379, host: 26379
  config.vm.network "forwarded_port", guest: 26380, host: 26380
  config.vm.network "forwarded_port", guest: 26381, host: 26381
end
