#!/usr/bin/env bash

VAGRANT_DIR=/home/vagrant/redis-scripts
VAGRANT_REDIS_CONF_DIR=$VAGRANT_DIR/redis-configs
REDIS_VERSION=stable
REDIS_DOWNLOAD_DIR=/home/vagrant/redis-downloads
REDIS_PACKAGE=redis-$REDIS_VERSION.tar.gz
REDIS_BUILD_DIR=$REDIS_DOWNLOAD_DIR/redis-$REDIS_VERSION
REDIS_DIR=/home/vagrant/redis
REDIS_BIN_DIR=$REDIS_DIR/bin
REDIS_CONF_DIR=$REDIS_DIR/conf
REDIS_SAVE_DIR=$REDIS_DIR/backups
REDIS_INSTANCES="7000 7001 7002 7003 7004 7005"
