name: Docs CI

on:
  push:
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
  schedule:
    - cron: '0 1 * * *' # nightly build

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}-docs
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

   build-docs:
     name: Build docs
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         with:
           python-version: 3.9
           cache: 'pip'
       - name: install deps
         run: |
           sudo apt-get update -yqq
           sudo apt-get install -yqq pandoc make
       - name: run code linters
         run: |
           pip install -r requirements.txt -r dev_requirements.txt -r docs/requirements.txt
           invoke build-docs

       - name: upload docs
         uses: actions/upload-artifact@v4
         with:
           name: redis-py-docs
           path: |
             docs/_build/html
